language: emacs-lisp

git:
  submodules: false

env:
  matrix:
    - EMACS=emacs-snapshot

install:
  sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
  sudo apt-get update -qq &&
  sudo apt-get install -qq emacs-snapshot;

before_script:
  emacs --version

script:
  emacs -Q --batch -L . -L ./emacs.d/conf -L ./eamcs.d/vendor \
  --eval "(progn (require 'init-bootstrap) (rr/unsafe-load-init-files))"